### ISSUE TITLE
Please can you output to stdout also the corresponding IP for each CN? 

### ISSUE THREAD

**Issue by rapbando** [bruston/cndump#2]
Hi,

Hoping that you don't mind I just created a [script](https://github.com/rapbando/maSSdump) using your nice program, could you add the above mentioned output?

Cheers!

**Comment by bruston** [comment]
The -u flag will output the corresponding URL. I forgot to document it in the readme, sorry.

```
[benjamin@irisa cndump]$ echo "157.240.240.35" | cndump -u
https://157.240.240.35 *.facebook.com
```

Does that help?

**Comment by rapbando** [comment]
Perfect!

`user@computer:~/maSSdump$` sudo bash maSSdump.sh 157.240.9.35/24
Starting masscan 1.3.2 (http://bit.ly/14GZzcT) at 2022-02-21 23:05:53 GMT
Initiating SYN Stealth Scan
Scanning 256 hosts [1 port/host]
[+] Looking up the certificate CNs for available hosts.....                  
---------------------------------------------------------------------

https://157.240.9.1 *.facebook.com
https://157.240.9.53 *.whatsapp.net
https://157.240.9.216 *.fbe2e.com
https://157.240.9.174 *.instagram.com
https://157.240.9.55 *.expresswifi.com
https://157.240.9.35 *.facebook.com
https://157.240.9.169 *.facebook.com
https://157.240.9.10 *.facebook.com
https://157.240.9.16 *.fb.com
https://157.240.9.2 *.facebook.com
https://157.240.9.34 *.facebook.com
https://157.240.9.40 *.facebook.com
https://157.240.9.18 *.facebook.com
https://157.240.9.133 *.fb.com
https://157.240.9.22 *.facebook.com
https://157.240.9.36 *.facebook.com
https://157.240.9.210 *.fb.com
https://157.240.9.9 *.facebook.com
https://157.240.9.26 *.extern.facebook.com

---------------------------------------------------------------------
Saved  domains to: out.massdump.txt
FINISH!!!`
